Sprint#12/9, iteration 1, filmorate
LeonidBS/java-filmorate pull request #7
Opened 2023-03-25 01:01 UTC by LeonidBS

2023-03-26 09:58 UTC, ohelly requested changes
Привет! В целом отличная работа, прекрасный код. Есть пара простых замечаний, которые следует исправить, также я оставил ряд рекомендаций, на которые стоит обратить внимание.

2023-03-26 09:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
Рекомендация: Рекомендую для полей идентификаторов использовать классы обертки(Long, Integer), так как они могут быть иметь значение null(по умолчанию) в отличии от примитивов, которые по умолчанию равны нулю. Таким образом мы сможем отслеживать, было ли задано значение или нет.

2023-03-26 09:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final String name;
Рекомендация: Для полей строк достаточно использования одной аннотации - ``@NotBlank``, так как она включает в себя проверку на != null.

2023-03-26 09:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @PastOrPresent(message = "Дата релиза указана в будущем")
Рекомендация: В данном случае наверное не стоит проверять дату релиза, в будущем она или нет, так как могут в систему завести фильм, который только выйдет, то есть заранее.

2023-03-26 09:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/validator/DateValidator.java
> +        return filmReleaseDate.isAfter(startDate);
Необходимо исправить: Следует добавить проверку на ``filmReleaseDate != null``, иначе если дату не задать при создании/обновлении выпадет ``NullPointerException``

2023-03-26 09:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotNull(message = "Отсутсвует email")
Рекомендация: Рекомендую для првоерки строк ипспользовать аннотацию ``@NotBlank``, так как она специально создана для них и включает в себя проверку на null и на проверку на пустоту.

2023-03-26 09:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final String login;
Рекомендация: Здесь также можно использовать только ``@NotBlank``

2023-03-26 09:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private int id;
АНалогичная рекомендация по использованию классов оберток, как в классе FIlm.

2023-03-26 09:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final List<Film> films = new ArrayList<>();
Рекомендация: Рекомендую использовать HashMap в качестве хракнилища, ключ у которой будет идентификатор фильма. Так будет проще доставать определенные фильмы, не итерируюясь по листу. Плюс скорость операций возрастет.

2023-03-26 09:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null) {
Рекомендация: Можно оба условия прописать в одном if'e, так код будет более читабельным: ``if (user.getName() == null || user.getName().isBlank()) {user.setName(uset.getLogin())}``

2023-03-26 09:58 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +
Необходимо исправить: При обновлении пользователя также необходимо проверять, что name != null, и в таком случае сетить туда логин.

2023-03-26 17:27 UTC, LeonidBS commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
Спасибо! Почему-то раньше не приходило в голову)), хотя вопрос к 0 по умолчанию возникал..

2023-03-26 17:28 UTC, LeonidBS commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final String name;
Буду читать документацию внимательнее)

2023-03-26 17:38 UTC, LeonidBS commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null) {
Время было "под утро"))

2023-03-26 17:39 UTC, LeonidBS commented
Исправлено по всем пунктам.

2023-03-26 18:16 UTC, LeonidBS commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final List<Film> films = new ArrayList<>();
Исправил. Подумал раз временный код (написано будем хранить в БД) , пусть будет попроще)).

2023-03-27 16:54 UTC, ohelly approved these changes
Привет! Все отлично, исправлены все замечания. Работу принимаю, можно двигаться дальаше. Удачи в дальнейшем обучении!

2023-03-28 14:37 UTC, merged