Sprint#13/10, iteration 1, filmorate, выполнение ТЗ№10
LeonidBS/java-filmorate pull request #8
Opened 2023-04-08 12:29 UTC by LeonidBS

Выполнение требований ТЗ№10. Pull Request на проверку.

2023-04-09 11:34 UTC, LeonidBS commented
Забыл отправить ссылку сразу)

2023-04-09 12:39 UTC, ohelly requested changes
Привет! Отлично проделанная работа! Есть одно небольшое замечание, которое необходимо поправить. Также я оставил ряд рекомендаций, на которые стоит обратить внимание.

2023-04-09 12:39 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        allFriends.put(friends, true);
Необходимо исправить: Метод удаления друзей, но судя по коду они наоборот добавлются

2023-04-09 12:39 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final UserStorage userStorage;
Рекомендация: Будет лучше заменить UserStorage на UserService, так как принято, что сервис обращается напрямую только к "своему" хранилищу, доступ к остальным осуществляется через сервисы.

2023-04-09 12:39 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.setLikes(assessmentMap);
Рекомендация: Сетить мапу обратно на 45 строке не обязательно, так как эта та же мапа, которую мы достали на 43 строке. То есть изменили содержимое объекта, но сам объект остался прежним.

2023-04-09 12:39 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getById(@PathVariable String id) {
Рекомендация: Чтобы избежать использование try/catch в контроллерах, можно параметр сразу использовать в нужном типе:
![image](https://user-images.githubusercontent.com/51891976/230772889-7111c685-6dd3-4a92-8aa5-c8b0f98bb46e.png)
Если передадут неверный формат, то спринг ее сам обработает и выкинет исключение.
Аналогично для всех остальных методов.

2023-04-10 05:22 UTC, LeonidBS commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    private final Map<Friends, Boolean> allFriends = new HashMap<>();
Если можно не буду переделывать. В ТЗ написано : _Есть много способов хранить информацию о том, что два пользователя являются друзьями. Например, можно создать свойство friends в классе пользователя, которое будет содержать список его друзей. Вы можете использовать такое решение или придумать своё._.   Я специально сделал хранение друзей и лайков по разному , чтобы сейчас сравнить решения и в дальнейшем смотреть , что лучше..

2023-04-10 06:37 UTC, LeonidBS commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        allFriends.put(friends, true);
Видимо в какой-то момент нечаянно откатил.  Исправил , также исправил тесты.

2023-04-10 06:43 UTC, LeonidBS commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final UserStorage userStorage;
Исправил добавлением метода findById в UserService . надеюсь такое решение приемлемо.

2023-04-10 06:45 UTC, LeonidBS commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.setLikes(assessmentMap);
Исправил. Спасибо!

2023-04-10 06:55 UTC, LeonidBS commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getById(@PathVariable String id) {
Исправил. Так и сделал сначала, а потом начал делать тесты и подумал , вдруг надо ловить самому)). Теперь буду знать). Спасибо!

2023-04-10 08:07 UTC, LeonidBS commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getById(@PathVariable String id) {
Тесты прошли. Отправляю.  Спасибо за проверку и оценку)!

2023-04-11 08:25 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    private final Map<Friends, Boolean> allFriends = new HashMap<>();
Да, конечно, можно не переделывать, рекомендация на то и рекомендация)

2023-04-11 08:27 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final UserStorage userStorage;
Да, это отличное решение, так и делают обычно

2023-04-19 11:34 UTC, merged